
import { Dictionary, TaxRates } from './types';

export const FUEL_CONSUMPTION_L_PER_100KM = 34; // Default value

export const TAX_RATES: TaxRates = {
  'Polska': { rate: 0.19, flag: '🇵🇱' },
  'Niemcy': { rate: 0.298, flag: '🇩🇪' },
  'Irlandia': { rate: 0.125, flag: '🇮🇪' },
  'Węgry': { rate: 0.09, flag: '🇭🇺' },
  'Rumunia': { rate: 0.16, flag: '🇷🇴' }
};

export const DICTIONARY: Dictionary = {
  pl: {
    headerTitle: "Kalkulator Kosztów Transportu",
    headerSubtitle: "Oblicz szacunkowy koszt i zysk trasy ciężarówki.",
    currencySettingsTitle: "Ustawienia Waluty",
    euroModeToggle: "Tryb EUR",
    refreshRateTitle: "Odśwież kurs Euro",
    currentRateLabel: "Aktualny Kurs:",
    distanceLabel: "Dystans do pokonania (km):",
    distancePlaceholder: "Wprowadź liczbę kilometrów",
    calcModeToggle: "Oblicz wg stawki za km",
    freightAmountLabel: (currency) => `Całkowita Kwota Frachtu (Przychód, ${currency}):`,
    freightAmountPlaceholder: "Wprowadź całkowitą kwotę za fracht (np. 1500.00)",
    ratePerKmLabel: (currency) => `Stawka za kilometr (${currency}/km):`,
    ratePerKmPlaceholder: "np. 5.50",
    customCostsTitle: "Indywidualne Stawki Kosztów",
    customCostsHint: "Wprowadź swoje rzeczywiste stawki. Zmiany są automatycznie uwzględniane w kalkulacji.",
    taxResidencyLabel: "Rezydencja Podatkowa (CIT)",
    fuelPriceLabel: "Cena Paliwa (PLN/L)",
    fuelConsumptionLabel: "Średnie Spalanie (L/100km)",
    tollCostLabel: "Opłaty Drogowe (PLN/km)",
    serviceCostLabel: "Serwis/Eksploatacja (PLN/km)",
    citOverheadLabel: "Narzut Przedsiębiorstwa (CIT)",
    resultsTitlePln: "Szczegółowe Obliczenia (w PLN)",
    resultsTitleEur: "Szczegółowe Obliczenia (w EUR)",
    totalRevenueTitle: "Całkowity Przychód Frachtu",
    distanceDisplayLabel: "Dystans:",
    costsSectionTitle: "A. Koszty Operacyjne",
    totalOpCostTitle: "Całkowity Koszt Operacyjny",
    profitBeforeTaxTitle: "B. Wynik Przed Opodatkowaniem (EBT)",
    earningsBeforeTaxTitle: "Dochód Brutto (Przychód - Koszty Operacyjne)",
    taxCostTitle: (rate) => `Koszt Podatku CIT (${rate} od dochodu brutto)`,
    profitSectionTitle: "C. Podsumowanie Zysku Netto",
    totalNetProfitTitle: "CAŁKOWITY ZYSK NETTO",
    netProfitPerKmTitle: "Zysk Netto na 1 km (na czysto)",
    suggestedPriceTitle: "Sugerowana Cena Końcowa (Koszt + Zysk 0%)",
    costFuel: (rate, consumption) => `1. Koszt Paliwa (${consumption}L/100km @ ${rate})`,
    costToll: (rate) => `2. Koszt Opłat Drogowych (${rate})`,
    costService: (rate) => `3. Koszt Serwisu/Eksploatacji (${rate})`,
    rateFetchError: (rate) => `Błąd pobierania kursu waluty. Użyto kursu zastępczego (${rate} PLN/EUR).`,
    languageButton: "Przełącz na angielski",
    tripDateLabel: "Data Trasy:",
    saveTripButton: "Zapisz Trasę",
    historyTitle: "Historia Obliczeń",
    loadButton: "Wczytaj",
    deleteButton: "Usuń",
    noHistory: "Brak zapisanych tras.",
    savedDateLabel: "Data:",
    filterDateFrom: "Data od:",
    filterDateTo: "Data do:",
    periodSummaryTitle: "Podsumowanie Wybranego Okresu",
    allHistorySummaryTitle: "Podsumowanie (Wszystkie Trasy)",
    periodTotalProfit: "Łączny Zysk Netto:",
    periodTotalDistance: "Łączny Dystans:",
    clearFilters: "Wyczyść filtry",
    
    // Auth
    loginTitle: "Logowanie",
    usernameLabel: "Nazwa użytkownika",
    passwordLabel: "Hasło",
    loginButton: "Zaloguj się",
    loginError: "Nieprawidłowa nazwa użytkownika lub hasło",
    welcomeUser: (name) => `Witaj, ${name}`,
    logoutButton: "Wyloguj",
    adminPanelButton: "Panel Administratora",
    backToCalculator: "Powrót do Kalkulatora",
    manageUsersTitle: "Zarządzanie Użytkownikami",
    addUserTitle: "Dodaj Nowego Użytkownika",
    roleLabel: "Rola",
    createUserButton: "Utwórz Użytkownika",
    deleteUserConfirm: "Czy na pewno chcesz usunąć tego użytkownika?",
    userCreatedSuccess: "Użytkownik został utworzony.",
    fillAllFields: "Wypełnij wszystkie pola.",
  },
  en: {
    headerTitle: "Transportation Cost Calculator",
    headerSubtitle: "Estimate the cost and profit of your truck route.",
    currencySettingsTitle: "Currency Settings",
    euroModeToggle: "EUR Mode",
    refreshRateTitle: "Refresh Euro Rate",
    currentRateLabel: "Current Exchange Rate:",
    distanceLabel: "Distance to Cover (km):",
    distancePlaceholder: "Enter the number of kilometers",
    calcModeToggle: "Calculate by rate per km",
    freightAmountLabel: (currency) => `Total Freight Amount (Revenue, ${currency}):`,
    freightAmountPlaceholder: "Enter the total freight amount (e.g., 1500.00)",
    ratePerKmLabel: (currency) => `Rate per Kilometer (${currency}/km):`,
    ratePerKmPlaceholder: "e.g. 1.25",
    customCostsTitle: "Individual Cost Rates",
    customCostsHint: "Enter your actual rates. Changes are automatically included in the calculation.",
    taxResidencyLabel: "Tax Residency (CIT)",
    fuelPriceLabel: "Fuel Price (PLN/L)",
    fuelConsumptionLabel: "Avg. Consumption (L/100km)",
    tollCostLabel: "Toll Costs (PLN/km)",
    serviceCostLabel: "Service/Maintenance (PLN/km)",
    citOverheadLabel: "Corporate Overhead (CIT)",
    resultsTitlePln: "Detailed Calculation (in PLN)",
    resultsTitleEur: "Detailed Calculation (in EUR)",
    totalRevenueTitle: "Total Freight Revenue",
    distanceDisplayLabel: "Distance:",
    costsSectionTitle: "A. Operational Costs",
    totalOpCostTitle: "Total Operational Cost",
    profitBeforeTaxTitle: "B. Earnings Before Tax (EBT)",
    earningsBeforeTaxTitle: "Gross Income (Revenue - Operational Costs)",
    taxCostTitle: (rate) => `CIT Tax Cost (${rate} calculated from gross income)`,
    profitSectionTitle: "C. Net Profit Summary",
    totalNetProfitTitle: "TOTAL NET PROFIT",
    netProfitPerKmTitle: "Net Profit per 1 km (Net)",
    suggestedPriceTitle: "Suggested Final Price (Operational Cost + 0% Profit)",
    costFuel: (rate, consumption) => `1. Fuel Cost (${consumption}L/100km @ ${rate})`,
    costToll: (rate) => `2. Toll Costs (${rate})`,
    costService: (rate) => `3. Service/Maintenance Costs (${rate})`,
    rateFetchError: (rate) => `Error fetching exchange rate. Fallback rate used (${rate} PLN/EUR).`,
    languageButton: "Switch to Polish",
    tripDateLabel: "Trip Date:",
    saveTripButton: "Save Trip",
    historyTitle: "Calculation History",
    loadButton: "Load",
    deleteButton: "Delete",
    noHistory: "No saved trips.",
    savedDateLabel: "Date:",
    filterDateFrom: "Date from:",
    filterDateTo: "Date to:",
    periodSummaryTitle: "Selected Period Summary",
    allHistorySummaryTitle: "Summary (All Trips)",
    periodTotalProfit: "Total Net Profit:",
    periodTotalDistance: "Total Distance:",
    clearFilters: "Clear filters",

    // Auth
    loginTitle: "Login",
    usernameLabel: "Username",
    passwordLabel: "Password",
    loginButton: "Sign In",
    loginError: "Invalid username or password",
    welcomeUser: (name) => `Welcome, ${name}`,
    logoutButton: "Logout",
    adminPanelButton: "Admin Panel",
    backToCalculator: "Back to Calculator",
    manageUsersTitle: "User Management",
    addUserTitle: "Add New User",
    roleLabel: "Role",
    createUserButton: "Create User",
    deleteUserConfirm: "Are you sure you want to delete this user?",
    userCreatedSuccess: "User created successfully.",
    fillAllFields: "Please fill all fields.",
  }
};
